server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:57799/railway
spring.datasource.username=root
spring.datasource.password=ajeusAIKowjtCcDkVgMjlfRpPsmlikrn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect